version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wewatch-server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "4000:4000"
    env_file:
      - .env
